version: "3"

services:
  springboot-app:
    image: bfiversionback/alpine:1.0.0
    restart: always
    build: .
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bfigroupe
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=0000
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8090:8090"
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      - POSTGRES_DB=bfigroupe
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5