version: "3"

services:
  springboot-app:
    image: bfiversionback/alpine:1.0.0
    restart: always
    build: .
    environment:
    ports:
      - "8090:8090"
    depends_on:
    - postgresql

  postgresql:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: bfigroupe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5353:5353"
