version: "3"

services:
  springboot-app:
    image: bfiversionback/alpine:1.0.0
    restart: always
    build: .
    environment:
      spring.datasource.url: jdbc:postgresql://localhost:5432/bfigroupe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000
    ports:
      - "8090:8090"
