version: "3"

services:
  springboot-app:
    image: bfiversionback/alpine:1.0.0
    restart: always
    build: .
    ports:
      - "8090:8090"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bfigroupe
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 0000

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: bfigroupe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
